# Generated by Django 3.2.9 on 2021-12-11 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=20, null=True)),
                ('last_name', models.TextField(max_length=20, null=True)),
                ('email', models.TextField(max_length=20, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('password', models.TextField(max_length=20, null=True)),
                ('created_at', models.DateField(null=True)),
                ('updated_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(null=True)),
                ('counter', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('poked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokedpokes', to='apps.user')),
                ('poker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokerpokes', to='apps.user')),
            ],
            options={
                'db_table': 'poke',
            },
        ),
    ]
